### ISSUE TITLE
Feature requests for next iteration

### ISSUE THREAD

**Issue by marcelwa** [whaaswijk/mugen#5]
Small feature requests for the next iteration:

- Timeout/conflict limit restriction
- Prohibit crossings to be PI/PO when disabling designated pins
- Allow crossings that are not strictly perpendicular. Two bent elements can also cross, i.e., a wire coming from the north going to the east can cross a wire coming from the south going to the west for instance.

**Comment by whaaswijk** [comment]
Good news: the first point has been implemented!

Regarding the second point: do you mean that when designated_io  is False, crossings cannot have PIs/POs as fanin?

**Comment by marcelwa** [comment]
Awesome!

And yes, that is exactly what I mean by that.

**Comment by whaaswijk** [comment]
So if i understand correctly this means that crosses can never have PI/PO fanin/fanout, since when designated_io is True, they cannot have it either.

**Comment by marcelwa** [comment]
That's absolutely correct.

**Comment by whaaswijk** [comment]
Closing this issue since all feature request have now been implemented.
